---

  - name: Add percona apt repository
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
      update_cache: yes

  - name: Enable pxc80 release
    command: percona-release enable pxc80

  - name: Install percona packages
    apt:
      pkg:
        - percona-xtradb-cluster-client
        - percona-xtradb-cluster-server
        - percona-xtradb-cluster
        - pmm2-client
      update_cache: yes

  - name: Start mysql service
    systemd:
      name: mysql
      state: started

  - name: Update mysql root password
    shell: >
      mysql -u root -NBe
      'ALTER USER "root"@"localhost"
      IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}"; FLUSH PRIVILEGES;'

  - name: Copy .my.cnf file with root password credentials.
    template:
      src: templates/root-my.cnf.j2
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: '0600'

  - name: Stop mysql service
    systemd:
      name: mysql
      state: stopped

  - name: Copy SSL CA certificate
    copy:
      src: files/ca.pem
      dest: /var/lib/mysql/ca.pem
      force: yes
      owner: mysql
      group: mysql
      mode: preserve

  - name: Copy SSL server-cert certificate
    copy:
      src: files/server-cert.pem
      dest: /var/lib/mysql/server-cert.pem
      force: yes
      owner: mysql
      group: mysql
      mode: preserve

  - name: Copy SSL server-key certificate
    copy:
      src: files/server-key.pem
      dest: /var/lib/mysql/server-key.pem
      force: yes
      owner: mysql
      group: mysql
      mode: preserve

  - name: Copy write-set replication config
    template:
      src: templates/wsrep.cnf.j2
      dest: /etc/mysql/percona-xtradb-cluster.conf.d/wsrep.cnf
      force: yes
      owner: root
      group: root
      mode: '0664'

...
